CREATE OR REPLACE PROCEDURE utils.clone_schema(from_schema text, to_schema text) AS
$BODY$
/* Developed by Ezequiel Tolnay, 2024-06. Released under the GNU General Public License v3.0 or later.
   Usage: CALL utils.clone_schema('source_schema', 'target_schema');
   This procedure clones the structure of a schema, including tables, enum types, and functions,
    but does not copy data. Only superusers can execute this procedure to prevent unauthorized schema cloning.
   Caller must be postgres user, to_schema must not exist, and from_schema must exist.
   All references to the original schema will be updated to point to the new schema, but references to other schemas will remain unchanged.
   It converts all serial columns and columns with default sequences to identity columns.
   Notes: Currently, it does not maintain ownership, permissions, or other schema-level properties.
          It does not retain original index or constraint names, using default naming instead.
          It also does not handle views, indexes, triggers, or other schema objects.
   TODO: Add support for views, indexes, triggers, ownership, permissions, and other schema objects.
         Add options to retain original names and properties, and to copy data if desired.
*/
DECLARE
    _sql text;
BEGIN
    IF CURRENT_USER NOT IN ('postgres') THEN -- Only allow superusers to clone schemas
        RAISE EXCEPTION 'Only superusers can clone a schema';
    END IF;

    EXECUTE format('CREATE SCHEMA %I', to_schema);
    EXECUTE format('SET SEARCH_PATH TO %I, public', to_schema);

    -- Enum types
    _sql := string_agg(regexp_replace(sql, format('\m%I\.', from_schema), to_schema||'.', 'g'), E';\n' ORDER BY typname)
    FROM (
        SELECT typname,
            format('CREATE TYPE %I AS ENUM (%s)',
                t.typname, string_agg(quote_literal(e.enumlabel), ', ' ORDER BY e.enumsortorder)) AS sql
        FROM pg_type t 
        JOIN pg_enum e ON t.oid = e.enumtypid  
        WHERE t.typnamespace = to_regnamespace(from_schema)
        GROUP BY t.typnamespace, t.typname
        ) x;
    IF _sql > '' THEN EXECUTE _sql; END IF;
    
    -- Tables
    _sql := string_agg(format('CREATE TABLE %I (LIKE %I.%1$I INCLUDING ALL)', relname, from_schema), E';\n' ORDER BY relname)
    FROM pg_class r
    WHERE r.relnamespace = to_regnamespace(from_schema)
      AND r.relkind = 'r';
    IF _sql > '' THEN EXECUTE _sql; END IF;

    -- Change serial to GENERATED BY DEFAULT
    _sql := string_agg(format('ALTER TABLE %s ALTER COLUMN %I DROP DEFAULT, ALTER COLUMN %2$I ADD GENERATED BY DEFAULT AS IDENTITY',
        r2.oid::regclass, a.attname), E';\n' ORDER BY r.relname, a.attnum)
    FROM pg_attribute a
    JOIN pg_class r ON (r.oid = a.attrelid)
    JOIN pg_depend d ON (d.refobjid = r.oid AND d.refobjsubid = a.attnum AND d.deptype = 'a')
    JOIN pg_class rd ON (rd.oid = d.objid AND rd.relkind = 'S')
    JOIN pg_class r2 ON (r2.relname = r.relname)
    WHERE r.relnamespace = to_regnamespace(from_schema)
      AND r2.relnamespace = to_regnamespace(to_schema)
      AND a.attnum > 0 AND a.attidentity = '';
    IF _sql > '' THEN EXECUTE _sql; END IF;

    -- Change sequences connected by default to GENERATED BY DEFAULT
    _sql := string_agg(format('ALTER TABLE %s ALTER COLUMN %I DROP DEFAULT, ALTER COLUMN %2$I ADD GENERATED BY DEFAULT AS IDENTITY',
        r.oid::regclass, a.attname), E';\n' ORDER BY r.relname)
    FROM pg_attribute a
    JOIN pg_class r ON (r.oid = a.attrelid)
    JOIN pg_attrdef d ON (d.adrelid = r.oid AND d.adnum = a.attnum)
    WHERE r.relnamespace = to_regnamespace(to_schema)
      AND a.attnum > 0
      AND a.atthasdef
      AND pg_get_expr(d.adbin, d.adrelid) ~ format('^nextval\(''%I\.', from_schema);
    IF _sql > '' THEN EXECUTE _sql; END IF;

    -- Change enum types from old schema to new schema
    _sql := string_agg(format('ALTER TABLE %s ALTER COLUMN %I TYPE %I USING %2$I::text::%3$I', r.oid::regclass, a.attname, t.typname),
        E';\n' ORDER BY r.oid::regclass::text, t.typname)
    FROM pg_attribute a
    JOIN pg_class r ON (r.oid = a.attrelid)
    JOIN pg_type t ON (t.oid = a.atttypid)
    WHERE r.relnamespace = to_regnamespace(to_schema)
      AND a.attnum > 0
      AND t.typnamespace = to_regnamespace(from_schema)
      AND t.typtype = 'e';
    IF _sql > '' THEN EXECUTE _sql; END IF;

    -- Copy foreign keys
    _sql := string_agg(sql, E';\n' ORDER BY oid::regclass::text)
    FROM (
        SELECT r2.oid, format('ALTER TABLE ONLY %I ADD FOREIGN KEY (%s) REFERENCES %I(%s) ON UPDATE %s ON DELETE %s',
            r2.relname, --CASE WHEN confupdtype = 'c' THEN 'CONSTRAINT ' || conname || ' ' ELSE '', 
            string_agg(quote_ident(a.attname), ', ' ORDER BY a.attnum), 
            r3.relname, string_agg(quote_ident(a3.attname), ', ' ORDER BY a3.attnum),
            CASE confupdtype
                WHEN 'a' THEN 'NO ACTION'
                WHEN 'r' THEN 'RESTRICT'
                WHEN 'c' THEN 'CASCADE'
                WHEN 'n' THEN 'SET NULL'
                WHEN 'd' THEN 'SET DEFAULT'
            END,
            CASE confdeltype
                WHEN 'a' THEN 'NO ACTION'
                WHEN 'r' THEN 'RESTRICT'
                WHEN 'c' THEN 'CASCADE'
                WHEN 'n' THEN 'SET NULL'
                WHEN 'd' THEN 'SET DEFAULT'
            END) AS sql
        FROM pg_constraint c
        JOIN pg_class r ON (r.oid = c.conrelid)
        JOIN pg_attribute a ON (a.attrelid = r.oid AND a.attnum = ANY(c.conkey))
        JOIN pg_class r2 ON (r2.relname = r.relname)
        JOIN pg_class r3 ON (r3.oid = c.confrelid)
        JOIN pg_attribute a3 ON (a3.attrelid = r3.oid AND a3.attnum = ANY(c.confkey))
        WHERE r.relnamespace = to_regnamespace(from_schema)
          AND r2.relnamespace = to_regnamespace(to_schema)
          AND c.contype = 'f'
        GROUP BY c.oid, r2.oid, r3.oid, c.confupdtype
        ) x;
    IF _sql > '' THEN EXECUTE _sql; END IF;

    -- Copy functions
    EXECUTE format('SET SEARCH_PATH TO %I, public', from_schema);
    _sql := string_agg(pg_get_functiondef(p.oid), E';\n' ORDER BY proname)
    FROM pg_proc p
    WHERE p.pronamespace = to_regnamespace(from_schema);
    _sql := regexp_replace(_sql, format('\m%I\M', from_schema), to_schema, 'g');
    EXECUTE format('SET SEARCH_PATH TO %I, public', to_schema);
    IF _sql > '' THEN EXECUTE _sql; END IF;
END;
$BODY$ LANGUAGE plpgsql;
